### ISSUE TITLE
Sort arrows on funkyheatmap are backwards

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/website-experimental#114]
I think a down arrow should mean descending and an up arrow should mean ascending

<img width="122" alt="image" src="https://user-images.githubusercontent.com/84813314/224072627-9d7adb53-ab5f-4d44-8fcb-5ba701195b8e.png">

**Comment by rcannood** [comment]
Good point :)

**Comment by scottgigante-immunai** [comment]
cc @LuckyMD

**Comment by rcannood** [comment]
Solved in #120
