### ISSUE TITLE
Method names overflow into heatmap

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/website-experimental#54]
Example: https://openproblems-experimental.netlify.app/results/dimensionality_reduction/

**Comment by rcannood** [comment]
How about we enforce a maximum character limit (suggestion: 50) on the method name? In the example you provided, I think `t-Distributed Stochastic Neighbor Embedding (t-SNE) (logCP10k, 1kHVG)` should simply be called `t-SNE (logCP10k, 1kHVG)` and `Principle Component Analysis (PCA) (logCP10k, 1kHVG)` should be called `PCA (logCP10k, 1kHVG)`.

In addition, I can make changes to the code such that, _if_ the character limit is exceeded, it shows the first 20 characters and the last 20 characters. This would render `t-Distributed Stochastic Neighbor Embedding (t-SNE) (logCP10k, 1kHVG)` as `t-Distributed Stoch ... ) (logCP10k, 1kHVG)`.

WDYT?

**Comment by scottgigante-immunai** [comment]
Seems reasonable to me. Abbreviations are described in the method summary anyway.

**Comment by rcannood** [comment]
Fixed thanks to openproblems-bio/openproblems#842 and #76.
