### ISSUE TITLE
Task cards on benchmarks page should not open in new tab

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/website-experimental#67]
Need to remove `target="_blank"`

**Comment by rcannood** [comment]
This is only affects PR previews. Because it's hosted at xxx--openproblems-experimental.netlify.app, it thinks it's an external website. 
I'll look into what's causing the issue, but at least it shouldn't affect the production website.

**Comment by KaiWaldrant** [comment]
that is exactly the reason.
