### ISSUE TITLE
funkyheatmap shows dataset IDs instead of names

### ISSUE THREAD

**Issue by scottgigante** [openproblems-bio/website-experimental#89]
Dataset names shown in the heatmap are wrong. E.g. for dimensionality reduction, for names on the heatmap are

Mouse Hspc Nestorowa2016
Olsson 2016 Mouse Blood
Tenx 5k Pbmc
Zebrafish Labs

but the actual dataset names are

Mouse hematopoietic stem cell differentiation
Mouse myeloid lineage differentiation
5k Peripheral blood mononuclear cells
Zebrafish

**Comment by rcannood** [comment]
Good point, let me finally fix that :)
